### PR TITLE
iSAM + LIDAR

### PR DESCRIPTION
**Pull request by gtinchev**
Example Usage:

Create the LIDAR clouds relative to poses every 15 estimates (controlled by -o)
1. se-vo-slam-lidar -L <logname.lcmlog> -d -o 15 -fr -frmin 0 -frmax 15 -pr 0 -fg -fgleft -80 -fgright 80
The rest of the parameters can be viewed with -h
2. Put your loop closures at the end of husky_isam_trajectory.txt (either manually or by another alogirhtm)
Run the iSAM algorithm selecting the directory w/ relative clouds and iSAM loop closures file.
2. se-isam-lidar -f husky_isam_trajectory.txt -cd isam-clouds/

The file will also attempt to extract a complete map b/w certain pose indices. Could possibly be moved as args in console (aint nobody got time for that)

@mauricefallon could you please review and accept?

### CODE REVIEW

**Comment by mauricefallon** [comment]
just had a quick look (not a full review):
- adds dift dependency through the filters. I'd want to remove that so that the vo itself doesnt depend on it
- for the dift filters I'd recommend non using LCM objects (bot_core::planar_lidar_t) in your classes. try to limit it to the application - but not in your classes
- should be able to merge se-vo-slam-lidar with se-vo-slam.

**Comment by mauricefallon** [comment]
I added features:
- supports any of the lidars: sick, multisense or Velodyne
- can also operate without LIDAR
- colors point clouds interestingly ;)

Examples for the three sensors:
https://www.dropbox.com/sh/nogsx918986kip6/AADopqUqeg2jZFODMlVyhPQsa?dl=0

**Comment by gtinchev** [comment]
I suggest implementing the ground points removal in cloud accumulate to remove the dift filters dependency.

**Comment by gtinchev** [comment]
Removed DIFT fitler dependency. Now depends on this pronto util: https://github.com/openhumanoids/pronto/pull/101
@mauricefallon Could you please review and accept both?

**Pull request merged**
